# spam classification

In [47]:
# nlp practice 
# spam classification 
import pandas as pd 
mesge=pd.read_csv('SMSSpamCollection.txt',sep='\t',names=['label','message'])

In [48]:
mesge

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [49]:
# data cleaning and preprocessing 
import re 
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\madhu\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [50]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
ps=PorterStemmer()
lemmatizer=WordNetLemmatizer()

In [94]:
corpus=[]
for i in range(0,len(mesge)):
    review=re.sub('[^a-zA-Z]',' ',mesge['message'][i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [95]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'searching right word thank breather promise wont take help granted fulfil promise wonderful blessing time',
 'date sunday',
 'xxxmobilemovieclub use credit click wap link next txt message click http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k watching',
 'eh u remember spell name yes v naughty make v wet',
 'fine way u feel way gota b',
 'england v macedonia dont miss goal team news txt ur national team eg england try wale scotland txt poboxox w wq',
 'seriously spell name',
 'going try month ha ha joking',
 'pay first lar da stock comin',
 'aft finish lunch go str lor ard smth lor u finish ur lunch already',
 'ffffffffff alright way meet sooner',
 'forced eat slice really hungry tho suck mark getting worried know sick turn pizza lol',
 'lol always convincing',
 'catch bus frying egg make tea eating mom left dinner feel love',
 'back amp packing car let know room',
 'ahhh work vaguely remember feel like lol',
 'wait still clear sure sarcastic x want live u',
 'yeah got v apologetic n fallen actin like spoilt child got caught till go badly cheer',
 'k tell anything',
 'fear fainting housework quick cuppa',
 'thanks subscription ringtone uk mobile charged month please confirm replying yes reply charged',
 'yup ok go home look timing msg xuhui going learn nd may lesson',
 'oops let know roommate done',
 'see letter b car',
 'anything lor u decide',
 'hello saturday go texting see decided anything tomo trying invite anything',
 'pls go ahead watt wanted sure great weekend abiola',
 'forget tell want need crave love sweet arabian steed mmmmmm yummy',
 'rodger burn msg tried call reply sm free nokia mobile free camcorder please call delivery tomorrow',
 'seeing',
 'great hope like man well endowed lt gt inch',
 'call message missed call',
 'get hep b immunisation nigeria',
 'fair enough anything going',
 'yeah hopefully tyler could maybe ask around bit',
 'u know stubborn even want go hospital kept telling mark weak sucker hospital weak sucker',
 'thinked first time saw class',
 'gram usually run like lt gt half eighth smarter though get almost whole second gram lt gt',
 'k fyi x ride early tomorrow morning crashing place tonight',
 'wow never realized embarassed accomodations thought liked since best could always seemed happy cave sorry give sorry offered sorry room embarassing',
 'sm ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end reply end sptv',
 'know mallika sherawat yesterday find lt url gt',
 'congrats year special cinema pas call c suprman v matrix starwars etc free bx ip pm dont miss',
 'sorry call later meeting',
 'tell reached',
 'yes gauti sehwag odi series',
 'gonna pick burger way home even move pain killing',
 'ha ha ha good joke girl situation seeker',
 'part checking iq',
 'sorry roommate took forever ok come',
 'ok lar double check wif da hair dresser already said wun cut v short said cut look nice',
 'valued customer pleased advise following recent review mob awarded bonus prize call',
 'today song dedicated day song u dedicate send ur valuable frnds first rply',
 'urgent ur awarded complimentary trip eurodisinc trav aco entry claim txt dis morefrmmob shracomorsglsuplt l aj',
 'hear new divorce barbie come ken stuff',
 'plane give month end',
 'wah lucky man save money hee',
 'finished class',
 'hi babe im home wanna something xx',
 'k k performed',
 'u call',
 'waiting machan call free',
 'thats cool gentleman treat dignity respect',
 'like people much shy pa',
 'operate lt gt',
 'still looking job much ta earn',
 'sorry call later',
 'k call ah',
 'ok way home hi hi',
 'place man',
 'yup next stop',
 'call later network urgnt sm',
 'real u getting yo need ticket one jacket done already used multis',
 'yes started send request make pain came back back bed double coin factory gotta cash nitros',
 'really still tonight babe',
 'ela kano il download come wen ur free',
 'yeah stand close tho catch something',
 'sorry pain ok meet another night spent late afternoon casualty mean done stuff moro includes time sheet sorry',
 'smile pleasure smile pain smile trouble pours like rain smile sum hurt u smile becoz someone still love see u smiling',
 'please call customer service representative pm guaranteed cash prize',
 'havent planning buy later check already lido got show e afternoon u finish work already',
 'free ringtone waiting collected simply text password mix verify get usher britney fml po box mk h ppw',
 'watching telugu movie wat abt u',
 'see finish load loan pay',
 'hi wk ok hols yes bit run forgot hairdresser appointment four need get home n shower beforehand cause prob u',
 'see cup coffee animation',
 'please text anymore nothing else say',
 'okay name ur price long legal wen pick u ave x am xx',
 'still looking car buy gone driving test yet',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'wow right mean guess gave boston men changed search location nyc something changed cuz signin page still say boston',
 'umma life vava umma love lot dear',
 'thanks lot wish birthday thanks making birthday truly memorable',
 'aight hit get cash',
 'would ip address test considering computer minecraft server',
 'know grumpy old people mom like better lying always one play joke',
 'dont worry guess busy',
 'plural noun research',
 'going dinner msg',
 'ok wif co like try new thing scared u dun like mah co u said loud',
 'gent trying contact last weekend draw show prize guaranteed call claim code k valid hr ppm',
 'wa ur openin sentence formal anyway fine juz tt eatin much n puttin weight haha anythin special happened',
 'entered cabin pa said happy b day bos felt special askd lunch lunch invited apartment went',
 'winner u specially selected receive holiday flight inc speak live operator claim p min',
 'goodo yes must speak friday egg potato ratio tortilla needed',
 'hmm uncle informed paying school directly pls buy food',
 'private account statement show unredeemed bonus point claim call identifier code expires',
 'urgent mobile awarded bonus caller prize final try contact u call landline box wr c ppm',
 'new address apple pair malarky',
 'today voda number ending selected receive award match please call quoting claim code standard rate app',
 'going sao mu today done',
 'predict wat time finish buying',
 'good stuff',
 'know yetunde sent money yet sent text bother sending dont involve anything imposed anything first place apologise',
 'room',
 'hey girl r u hope u r well del r bak long time c give call sum time lucyxx',
 'k k much cost',
 'home',
 'dear call tmorrow pls accomodate',
 'first answer question',
 'sunshine quiz wkly q win top sony dvd player u know country algarve txt ansr sp tyrone',
 'want get laid tonight want real dogging location sent direct ur mob join uk largest dogging network bt txting gravel nt ec p msg p',
 'haf msn yijue hotmail com',
 'call meet',
 'check room befor activity',
 'rcv msg chat svc free hardcore service text go u get nothing u must age verify yr network try',
 'got c lazy type forgot lect saw pouch like v nice',
 'k text way',
 'sir waiting mail',
 'swt thought nver get tired little thing lovable person coz somtimes little thing occupy biggest part heart gud ni',
 'know pls open back',
 'yes see ya dot',
 'whats staff name taking class u',
 'freemsg replied text randy sexy female live local luv hear u netcollex ltd p per msg reply stop end',
 'ummma call check life begin qatar pls pray hard',
 'k deleted contact',
 'sindu got job birla soft',
 'wine flowing nevering',
 'yup thk cine better co need go plaza mah',
 'ok ur typical reply',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'everywhere dirt floor window even shirt sometimes open mouth come flowing dream world without half chore time joy lot tv show see guess like thing must exist like rain hail mist time done become one',
 'aaooooright work',
 'leaving house',
 'hello love get interview today happy good boy think missing',
 'customer service annoncement new year delivery waiting please call arrange delivery',
 'winner u specially selected receive cash holiday flight inc speak live operator claim',
 'keep safe need miss already envy everyone see real life',
 'new car house parent new job hand',
 'love excited day spend make happy',
 'pls stop bootydelious f inviting friend reply yes see www sm ac u bootydelious stop send stop frnd',
 'bangbabes ur order way u receive service msg download ur content u goto wap bangb tv ur mobile internet service menu',
 'place ur point e culture module already',
 'urgent trying contact last weekend draw show prize guaranteed call claim code valid hr',
 'hi frnd best way avoid missunderstding wit beloved one',
 'great escape fancy bridge need lager see tomo',
 'yes completely form clark also utter waste',
 'sir need axis bank account bank address',
 'hmmm thk sure got time hop ard ya go free abt muz call u discus liao',
 'time coming later',
 'bloody hell cant believe forgot surname mr ill give u clue spanish begin',
 'well gonna finish bath good fine night',
 'let know got money carlos make call',
 'u still going mall',
 'turn friend staying whole show back til lt gt feel free go ahead smoke lt gt worth',
 'text doesnt reply let know log',
 'hi spoke maneesha v like know satisfied experience reply toll free yes',
 'lifted hope offer money need especially end month approach hurt studying anyways gr weekend',
 'lol u trust',
 'ok gentleman treat dignity respect',
 'guy close',
 'going nothing great bye',
 'hello handsome finding job lazy working towards getting back net mummy boytoy miss',
 'haha awesome minute',
 'please call customer service representative freephone pm guaranteed cash prize',
 'got xmas radio time get',
 'jus reached home go bathe first si using net tell u finish k',
 'unique enough find th august www areyouunique co uk',
 'sorry joined league people dont keep touch mean great deal friend time even great personal cost great week',
 'hi finally completed course',
 'stop however suggest stay someone able give or every stool',
 'hope settled new school year wishin gr day',
 'gud mrng dear hav nice day',
 'u got person story',
 'hamster dead hey tmr meet pm orchard mrt',
 'hi kate evening hope see tomorrow bit bloody babyjontet txt back u xxx',
 'found enc lt gt',
 'sent lt gt buck',
 'hello darlin ive finished college txt u finish u love kate xxx',
 'account refilled successfully inr lt decimal gt keralacircle prepaid account balance r lt decimal gt transaction id kr lt gt',
 'goodmorning sleeping ga',
 'u call alter ok',
 'say like dat dun buy ericsson oso cannot oredi lar',
 'entered cabin pa said happy b day bos felt special askd lunch lunch invited apartment went',
 'aight yo dat straight dogg',
 'please give u connection today lt decimal gt refund bill',
 'shoot big load get ready',
 'bruv hope great break rewarding semester',
 'home always chat',
 'k k good study well',
 'yup noe leh',
 'sound great home',
 'finally match heading towards draw prediction',
 'tired slept well past night',
 'easy ah sen got selected mean good',
 'take exam march',
 'yeah think use gt atm register sure anyway help let know sure ready',
 'ok prob take ur time',
 'o called ubandu run without installing hard disk use o copy important file system give repair shop',
 'sorry call later',
 'u say leh course nothing happen lar say v romantic jus bit lor thk e nite scenery nice leh',
 'new mobile must go txt nokia collect today www tc biz optout gbp mtmsg',
 'would really appreciate call need someone talk',
 'u meet ur dream partner soon ur career flyng start find free txt horo followed ur star sign e g horo aries',
 'hey company elama po mudyadhu',
 'life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lesson happy morning',
 'dear good morning',
 'get gandhipuram walk cross cut road right side lt gt street road turn first right',
 'dear going rubber place',
 'sorry battery died yeah',
 'yes tv always available work place',
 'text meet someone sexy today u find date even flirt u join p reply name age eg sam msg recd thirtyeight penny',
 'printed oh lt gt come upstairs',
 'ill little closer like bus stop street',
 'wil reach',
 'new theory argument win situation loses person dont argue ur friend kick amp say always correct',
 'u secret admirer looking make contact u find r reveal think ur special call',
 'tomarrow final hearing laptop case cant',
 'pleassssssseeeeee tel v avent done sportsx',
 'okay shining meant signing sound better',
 'although told u dat baig face watch really like e watch u gave co fr u thanx everything dat u done today touched',
 'u remember old commercial',
 'late said website dont slipper',
 'asked call ok',
 'kallis wont bat nd inning',
 'didnt work oh ok goodnight fix ready time wake dearly missed good night sleep',
 'congratulation ur awarded cd voucher gift guaranteed free entry wkly draw txt music tncs www ldew com win ppmx age',
 'ranjith cal drpd deeraj deepak min hold',
 'wen ur lovable bcums angry wid u dnt take seriously coz angry childish n true way showing deep affection care n luv kettoda manda nice day da',
 '',
 'ups day also shipping company take wks way usps take week get lag may bribe nipost get stuff',
 'back lemme know ready',
 'necessarily expect done get back though headin',
 'mmm yummy babe nice jolt suzy',
 'lover need',
 'tried contact reply offer video handset anytime network min unlimited text camcorder reply call',
 'parked next mini coming today think',
 'yup',
 'anyway going shopping co si done yet dun disturb u liao',
 'luton ring ur around h',
 'hey really horny want chat see naked text hot text charged pm unsubscribe text stop',
 'dint come u',
 'wana plan trip sometme',
 'sure yet still trying get hold',
 'ur ringtone service changed free credit go club mobile com choose content stop txt club stop p wk club po box mk wt',
 'evo download flash jealous',
 'ringtone club get uk single chart mobile week choose top quality ringtone message free charge',
 'come mu sorting narcotic situation',
 'night ended another day morning come special way may smile like sunny ray leaf worry blue blue bay',
 'hmv bonus special pound genuine hmv voucher answer easy question play send hmv info www percent real com',
 'usf guess might well take car',
 'objection bf coming',
 'thanx',
 'tell rob mack gf theater',
 'awesome see bit',
 'sent type food like',
 'done handed celebration full swing yet',
 'got called tool',
 'wen u miss someone person definitely special u person special miss keep touch gdeve',
 'ok asked money far',
 'okie',
 'yeah think usual guy still passed last night get ahold anybody let know throw',
 'k might come tonight class let early',
 'ok',
 'hi baby im cruisin girl friend r u give call hour home thats alright fone fone love jenny xxx',
 'life mean lot love life love people life world call friend call world ge',
 'dear shall mail tonite busy street shall update tonite thing looking ok varunnathu edukkukayee raksha ollu good one real sense',
 'hey told name gautham ah',
 'haf u found feel stupid da v cam working',
 'oops got bit',
 'much buzy',
 'accidentally deleted message resend please',
 'mobile customer may claim free camera phone upgrade pay go sim card loyalty call offer end thfeb c apply',
 'unless situation go gurl would appropriate',
 'hurt tease make cry end life die plz keep one rose grave say stupid miss u nice day bslvyl',
 'cant pick phone right pls send message',
 'need coffee run tomo believe time week already',
 'awesome remember last time got somebody high first time diesel v',
 'shit really shocking scary cant imagine second def night u think somewhere could crash night save taxi',
 'oh way food fridge want go meal tonight',
 'womdarfull actor',
 'sm ac blind date u rodds aberdeen united kingdom check http img sm ac w icmb cktz r blind date send hide',
 'yup remb think book',
 'jos ask u wana meet',
 'lol yes friendship hanging thread cause u buy stuff',
 'themob check newest selection content game tone gossip babe sport keep mobile fit funky text wap',
 'garage key bookshelf',
 'today accept day u accept brother sister lover dear best clos lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rply mean enemy',
 'think ur smart win week weekly quiz text play c winnersclub po box uz gbp week',
 'say give call friend got money definitely buying end week',
 'hi way u day normal way real ur unique hope know u rest mylife hope u find wot lost',
 'made day great day',
 'k k advance happy pongal',
 'hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk got lo oso forgot liao',
 'really dude friend afraid',
 'december mobile mths entitled update latest colour camera mobile free call mobile update co free',
 'coffee cake guess',
 'merry christmas babe love ya kiss',
 'hey dont go watch x men lunch haha',
 'cud u tell ppl im gona b bit l co bus hav gon past co full im still waitin pete x',
 'would great guild could meet bristol road somewhere get touch weekend plan take flight good week',
 'problem',
 'call message missed call',
 'hi da today class',
 'say good sign well know track record reading woman',
 'cool text parked',
 'reading text sent meant joke read light',
 'k k apo k good movie',
 'maybe could get book tomo return immediately something',
 'call germany penny per minute call fixed line via access number prepayment direct access',
 'chance might evaporated soon violated privacy stealing phone number employer paperwork cool please contact report supervisor',
 'valentine day special win quiz take partner trip lifetime send go p msg rcvd custcare',
 'ta daaaaa home babe still',
 'cool come havent wined dined',
 'sleeping surfing',
 'sorry call later',
 'u calling right call hand phone',
 'ok great thanx lot',
 'take post come must text happy reading one wiv hello caroline end favourite bless',
 'u hiding stranger',
 'interested like',
 'sister cleared two round birla soft yesterday',
 'gudnite tc practice going',
 'dis yijue jus saw ur mail case huiming havent sent u num dis num',
 'one small prestige problem',
 'fancy shag interested sextextuk com txt xxuk suzy txts cost per msg tncs website x',
 'checking really miss seeing jeremiah great month',
 'nah help never iphone',
 'car hour half going apeshit',
 'today sorry day ever angry ever misbehaved hurt plz plz slap urself bcoz ur fault basically good',
 'yo guy ever figure much need alcohol jay trying figure much safely spend weed',
 'lt gt ish minute minute ago wtf',
 'thank calling forgot say happy onam sirji fine remembered met insurance person meet qatar insha allah rakhesh ex tata aig joined tissco tayseer',
 'congratulation ur awarded cd voucher gift guaranteed free entry wkly draw txt music tncs www ldew com win ppmx age',
 'ur cash balance currently pound maximize ur cash send cash p msg cc hg suite land row w j hl',

In [53]:
len(corpus)

5572

In [60]:
# out put features 
y=pd.get_dummies(mesge['label'],dtype='float')
y

      ham  spam
0     1.0   0.0
1     1.0   0.0
2     0.0   1.0
3     1.0   0.0
4     1.0   0.0
...   ...   ...
5567  0.0   1.0
5568  1.0   0.0
5569  1.0   0.0
5570  1.0   0.0
5571  1.0   0.0

[5572 rows x 2 columns]

In [61]:
y=y.iloc[:,0].values

In [62]:
#train test split 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [63]:
X_train

['so amount get pls',
 'ok lor early still project meeting',
 'one small prestige problem',
 'making easy pay back lt gt yr say pay back earlier get',
 'lol mad first woke gave',
 'anything',
 'thanx lot',
 'ok lor',
 'k head min see',
 'usual u call ard smth',
 'u reckon need arrange transport u thanks',
 'mum going robinson already',
 'bognor splendid time year',
 'would still cozy exhausted last night nobody went school work everything closed',
 'see shadow get early spring yay',
 'lol boo hoping laugh',
 'tot group mate lucky havent reply wat time need leave',
 'stop story told returned saying order',
 'problem baby good time talk called left message',
 'da run activate full version da',
 'life face choice toss coin becoz settle question coin air u know heart hoping gudni',
 'probably eat today think gonna pop weekend u miss',
 'r u cooking dinner',
 'call ok said call',
 'know called',
 'actually fuck whatever find excuse tampa point january though',
 'havent got da topic yet rite',
 'valued customer pleased advise following recent review mob awarded bonus prize call',
 'sorry u unsubscribe yet mob offer package min term week pls resubmit request expiry reply themob help info',
 'yun buying school got offer plus',
 'didnt complete gist oh',
 'aiyo co sm neva reply wait reply lar tot havent finish ur lab wat',
 'get hep b immunisation nigeria',
 'meet library',
 'go ok na',
 'ur balance ur next question sang uptown girl answer txt ur answer good luck',
 'oh gei happend tron maybe ill dl',
 'k yan jiu liao sat go bugis vill one frm den hop parco nb sun go cine frm den hop orc mrt hip hop',
 'call message missed call',
 'sport fan get latest sport news str ur mobile wk free plus free tone txt sport www getzed co uk norm txt p',
 'mm umma ask vava also come tell play later together',
 'know u u know send chat let find p msg rcvd hg suite land row w j hl ldn year',
 'ffffffffff alright way meet sooner',
 'hope good week checking',
 'ok ill tell company',
 'cbe chennai',
 'ok finishing soon',
 'india win level series mean record',
 'storming msg wen u lift phne u say hello u knw wt real meaning hello name girl yes u knw dat girl margaret hello girlfrnd f grahmbell invnted telphone moral one get name person bt girlfrnd g n g h',
 'world running still maybe feeling admit mad correction let call life keep running world may u r also running let run',
 'hope good week checking',
 'course tease know simply must see grin keep posted prey loving smile devouring kiss',
 'amazing quote sometimes life difficult decide whats wrong lie brings smile truth brings tear',
 'flirting txt girl bloke ur name age eg girl zoe join get chatting',
 'two carton u pleased shelf',
 'white fudge oreo store',
 'free text msg text ok credit account',
 'bad girl lady',
 'stitch trouser',
 'k girl waiting reception ah',
 'love cuddle want hold strong arm right',
 'ready call',
 'fighting world easy u either win lose bt fightng close u dificult u lose u lose u win u still lose',
 'make tonight',
 'dear chechi talk',
 'u still going mall',
 'tell reached',
 'havent planning buy later check already lido got show e afternoon u finish work already',
 'bloody hell cant believe forgot surname mr ill give u clue spanish begin',
 'txting driving',
 'life style garment account please',
 'audrie lousy autocorrect',
 'ever green quote ever told jerry cartoon person irritates u always one love u vry much fails express gud nyt',
 'dear going rubber place',
 'lol need cash nitros hurry come crash',
 'good morning dear great amp successful day',
 'camera awarded sipix digital camera call fromm landline delivery within day',
 'k give back thanks',
 'lasting much hour might get lucky',
 'gonna death gonna leave note say robs fault avenge',
 'checking',
 'sorry chikku cell got problem thts nt able reply u msg u',
 'really crashed cuddled sofa',
 'hey inconvenient si huh',
 'got divorce lol',
 'oh k come tomorrow',
 'ups day also shipping company take wks way usps take week get lag may bribe nipost get stuff',
 'pls send correct name da',
 'mum sent many many message since got want know actually getting enjoy rest day',
 'number sir',
 'yavnt tried yet never played original either',
 'want go',
 'thanks ringtone order reference charged gbp per week unsubscribe anytime calling customer service',
 'get cash together text jason',
 'check room befor activity',
 'know god created gap finger one made come amp fill gap holding hand love',
 'hi u decide wot get bday ill prob jus get voucher frm virgin sumfing',
 'mean get door',
 'smile pleasure smile pain smile trouble pours like rain smile sum hurt u smile becoz someone still love see u smiling',
 'mean fat head',
 'cheer lou yeah goodnite shame u neva came c ya gailxx',
 'rose red red blood blood heart heart u u send ti ur friend including u like u get back u r poor relation u need support u r frnd many luvs u praying god marry u try',
 'medical mission nigeria',
 'really need kiss u miss u baby ur baby eva',
 'u win music gift voucher every week starting txt word draw tscs www idew com skillgame winaweek age ppermesssubscription',
 'got message ignoring yes shopping',
 'day euro kickoff u kept informed latest news result daily unsubscribe send get euro stop',
 'also remember get dobby bowl car',
 'honeybee said sweetest world god laughed amp said wait u havnt met person reading msg moral even god crack joke gm gn ge gn',
 'nvm going wear sport shoe anyway going late leh',
 'also andros ice etc etc',
 'many time told stage use laugh listen aha',
 'well still bit left guy want tonight',
 'yo guess dropped',
 'hi probably much fun get message thought id txt u co im bored james farting night',
 'dont want hear philosophy say happen',
 'little med say take every hour pain back took another hope die',
 'bought test yesterday something let know exact day u ovulate get u wks pls pls dont fret know u r worried pls relax also anything ur past history u need tell',
 'possible teach',
 'ok arm feeling weak cuz got shot go another time',
 'love come took long leave zaher got word ym happy see sad left miss',
 'hi kate lovely see tonight ill phone tomorrow got sing guy gave card xxx',
 'oh ya ya remember da',
 'happy birthday may u find ur prince charming soon n dun work hard',
 'simpson movie released july name band died start film green day b blue day c red day send b c',
 'ok need tell anything going sleep good night',
 'guy browsin compulsory',
 'olol printed forum post guy exact prob fixed gpu replacement hopefully dont ignore',
 'notice like looking shit mirror youre turning right freak',
 'si catching e show e afternoon watching w c u wan watch today tmr lor',
 'interested like',
 'hi moved pub would great c u u cud come',
 'oh thats late well good night give u call tomorrow iam going go sleep night night',
 'broke list reason nobody town tell sarcastic faggy',
 'yetunde class run water make ok pls',
 'awesome remember last time got somebody high first time diesel v',
 'thinked first time saw class',
 'urgent mobile number awarded prize guaranteed call land line claim valid hr',
 'sign maturity start saying big thing actually start understanding small thing nice evening bslvyl',
 'love wine dine lady',
 'nah im goin wrks j wot bout u',
 'yeah basically time next week get away mom amp get',
 'greeting consider excused',
 'oh god almost home',
 'u call lunch',
 'thanx lot ur help',
 'able sleep',
 'keep ten r shelf buy two egg',
 'yup hey one day fri ask miwa jiayin take leave go karaoke',
 'yes thought thanks',
 'might come kerala day prepared take leave finalise dont plan travel visit need finish urgent work',
 'busy trying finish new year looking forward finally meeting',
 'hi ibh customer loyalty offer new nokia mobile txtauction txt word start get',
 'wrong phone phone answer one assume people well',
 'ok ok guess',
 'otherwise part time job na tuition',
 'hey veggie pizza',
 'oh way food fridge want go meal tonight',
 'sure whenever show fuck gt',
 'e admin building might b slightly earlier call u reaching',
 'going orchard laready reaching soon u reaching',
 'stupid possible',
 'izzit still raining',
 'way school pls send ashley number',
 'sorry vikky watching olave mandara movie kano trishul theatre wit frnds',
 'yet like keep touch easiest way barcelona way ru house',
 'network operator service free c visit biz',
 'ill call evening ill idea',
 'add really care least get dude fuck hey money want',
 'reckon need town eightish walk carpark',
 'uncle timi help clearing car',
 'lol forgot eh yes bring babe',
 'new message please call',
 'wat uniform get',
 'v nice sheffield tom air opinion category b used measure ethnicity next census busy transcribing',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'affidavit say lt gt e twiggs st division g courtroom lt gt lt time gt double check text tomorrow',
 'free entry weekly comp send word enter c www textcomp com cust care',
 'freemsg record indicate may entitled pound accident claim free reply yes msg opt text stop',
 'babe go day sip cappuccino think love send kiss across sea',
 'better bb wont use wife doctor',
 'oh shit thought trip loooooool make much sense grin sofa reference sleep couch link sent went trip oh babe go celebration rent',
 'new theory argument win situation loses person dont argue ur friend kick amp say always correct',
 'best msg hard person u know one step foward make u fall love amp one step back ruin ur friendship good night',
 'long quit get like minute day',
 'network allow company bill sm responsible supplier shop give guarantee sell b g',
 'world happiest frnds never character dey best understanding difference',
 'dare stupid wont tell anything hear wont talk',
 'u ask darren go n pick u lor oso sian tmr haf meet lect',
 'movie collect car oredi',
 'guess lt gt min',
 'thing change sentence want concentrate educational career im leaving',
 'sorry call later',
 'ya ok dinner',
 'good hear',
 'jus reached home go bathe first si using net tell u finish k',
 'aight chillin friend room text way',
 'lol alright thinkin haha',
 'comin fetch u oredi',
 'mm yes dear look hugging p',
 'evening v good somewhat event laden fill worry head ok throat wrecked see six',
 'said right giggle saw u would possibly first person die nvq think much could',
 'hot live fantasy call p per min ntt ltd po box croydon cr wb k',
 'pay like lt gt yr difficult',
 'thanks yesterday sir wonderful hope enjoyed burial mojibiola',
 'thank meet monday',
 'watching cartoon listening music amp eve go temple amp church u',
 'much u trying get',
 'best line said love wait till day forget u day u realize u cannot forget gn',
 'might want pull case plan spending much confidence derek taylor money management',
 'dare change ring',
 'want tel u one thing u mistake k message sent',
 'get ready moan scream',
 'able anything',
 'opinion jada kusruthi lovable silent spl character matured stylish simple pls reply',
 'seems unnecessarily hostile',
 'well meant opposed drunken night',
 'meet depends wan lor',
 'boltblue tone p reply poly mono eg poly cha cha slide yeah slow jamz toxic come stop tone txt',
 'pls stop bootydelious f inviting friend reply yes see www sm ac u bootydelious stop send stop frnd',
 'see letter b car',
 'er mw im filled tuth aight',
 'gud ni dear slp well take care swt dream muah',
 'might ax well im',
 'come online today night',
 'chikku nt yet ya free',
 'prakesh know',
 'hard believe thing like say lie think twice saying anything',
 'oops thk dun haf enuff go check tell',
 'ok',
 'still grinder',
 'lol well without could big sale together',
 'dont shall buy one dear',
 'exhausted train morning much wine pie sleep well',
 'cooked rather nice salmon la',
 'dad went oredi',
 'lt gt k oh send home sale',
 'thesmszone com let send free anonymous masked message im sending message see potential abuse',
 'r comin back dinner',
 'win winner mr foley ipod exciting prize soon keep eye ur mobile visit www win co uk',
 'wil lt gt minute got space',
 'hi darlin hope nice night wish come cant wait see love fran p want dirty anal sex want man gang bang',
 'u still plumber tape wrench could borrow',
 'private account statement show un redeemed point call identifier code expires',
 'yes saw message',
 'ok another number',
 'u find time bus coz need sort stuff',
 'wait still clear sure sarcastic x want live u',
 'noe la u wana pei bf oso rite k lor day den',
 'dont think need yellow card uk travel ask someone gone lt gt buck',
 'surely dont forgot come always touch',
 'nothing got msg frm tht unknown',
 'geeee miss already know think fuck wait till next year together loving kiss',
 'yeah confirmed staying weekend',
 'mah b pick tomorrow',
 'unless situation go gurl would appropriate',
 'ok lor anyway thk cant get ticket co like quite late already u wan go look ur frens darren wif',
 'want new nokia colour phone deliveredtomorrow free minute mobile free text free camcorder reply call',
 'usually person unconscious child adult may behave abnormally call',
 'lookatme thanks purchase video clip lookatme charged p think better send video mmsto',
 'miserable tell u side effect birth control massive gut wrenching cramp first month sleep last night',
 'hospital da return home evening',
 'course make stink',
 'pls ask macho much budget bb bold co saw new one lt gt dollar',
 'use foreign stamp whatever send',
 'thankyou much call appreciate care',
 'took tablet reaction morning',
 'thanks sending mental ability question',
 'mean u could keep ur word',
 'u win music gift voucher every week starting txt word draw tscs www idew com skillgame winaweek age ppermesssubscription',
 'mobile customer may claim free camera phone upgrade pay go sim card loyalty call offer end thfeb c apply',
 'unbelievable faglord',
 'come home one last time wont anything trust',
 'dun believe leh tot told true already thk muz c u tog believe',
 'superior telling friday leave department except leave way call waheed fathima hr conform',
 'went project centre',
 'u coming back dinner rite dad ask confirm wif u',
 'well weather cali great complexity great need car move freely tax outrageous great place sad part missing home',
 'aww must nearly dead well jez iscoming todo workand whilltake forever',
 'meeting darren',
 'lost help',
 'know u u know send chat let find p msg rcvd hg suite land row w j hl ldn year',
 'cant pick phone right pls send message',
 'pls dont forget study',
 'get step outta way congrats',
 'dunno lei might b eatin wif frens wan eat wait lar',
 'much ur hdd casing cost',
 'lol ok forgiven',
 'hi please get lt gt dollar loan pay back mid february pls',
 'born god said oh another idiot born god said oh competition knew one day two become freinds forever',
 'fair enough anything going',
 'sir waiting mail',
 'know anthony bringing money school fee pay rent stuff like thats need help friend need',
 'ard lor ok message lor',
 'wen ur lovable bcums angry wid u dnt take seriously coz angry childish n true way showing deep affection care n luv kettoda manda nice day da',
 'always make thing bigger',
 'people mu table lambda',
 'cute thought friendship necessary share every secret ur close frnd watever u shared true',
 'oh oh wasted den muz chiong sat n sun liao',
 'take phone callon friday assume year',
 'hi test lt gt rd',
 'take exam march',
 'r home come within min',
 'one slice one breadstick lol',
 'call germany penny per minute call fixed line via access number prepayment direct access',
 'lt gt mca conform',
 'yes watching footie worried going blow phil neville',
 'want get laid tonight want real dogging location sent direct ur mob join uk largest dogging network bt txting gravel nt ec p msg p',
 'stop old man get build snowman snow angel snowball fight',
 'okey dokey bit sorting stuff',
 'time u wrkin',
 'want get laid tonight want real dogging location sent direct ur mob join uk largest dogging network txting moan nyt ec p msg p',
 'ok lar u sleep early nite',
 'much getting',
 'must come later normally bathe da afternoon mah',
 'back work morro half term u c nite sexy passion b go back chat luv dena call minmobsmorelkpobox hp fl',
 'da whats plan',
 'remains bro amongst bros',
 'today song dedicated day song u dedicate send ur valuable frnds first rply',
 'know god created gap finger one made come amp fill gap holding hand love',
 'dear cherthala case u r coming cochin pls call bfore u start shall also reach accordingly tell day u r coming tmorow engaged an holiday',
 'okies go yan jiu skip ard oso go cine den go mrt one blah blah blah',
 'run away frm u walk slowly amp kill u care enough stop',
 'wat time wan today',
 'hey babe friend cancel still visit',
 'freemsg claim ur sm message text ok use web mobile ur mate etc join txt com p wk c box la wu remove txtx stop',
 'yo know anyone lt gt otherwise able buy liquor guy flaked right get hold somebody loko night',
 'goal arsenal henry v liverpool henry score simple shot yard pas bergkamp give arsenal goal margin min',
 'ok take care umma',
 'omg want scream weighed lost weight woohoo',
 'jade paul u txt u remember barmed want talk u txt',
 'camera quite good mega pixel optical digital doom lovely holiday safe hope hav good journey happy new year see couple week',
 'u r much close heart u go away shattered plz stay',
 'said matter mind saying matter',
 'alright omw gotta change order half th',
 'gone get info bt dont know',
 'greatest test courage earth bear defeat without losing heart gn tc',
 'fishrman woke early mrng dark waited amp found sack ful stone strtd throwin thm sea pas time atlast jus stone sun rose amp found tht r nt stone diamond moral dont wake early mrng good night',
 'movie laptop',
 'sunshine quiz wkly q win top sony dvd player u know country liverpool played mid week txt ansr sp tyrone',
 'thanks loving rock',
 'actually decided hungry left yet v',
 'great shoot big load get ready',
 'jus finish bathing',
 'hows favourite person today r u workin hard sleep last nite nearly rang u',
 'holy living christ taking long',
 'actual exam harder nbme',
 'move morphine',
 'private account statement show un redeemed point call identifier code expires',
 'urgent mobile bonus caller prize nd attempt reach call asap box n qp ppm',
 'look like u wil b getting headstart im leaving bout ish u r desperate company could head earlier goin meet rummer',
 'wen ur lovable bcums angry wid u dnt take seriously coz angry childish n true way showing deep affection care n luv kettoda manda nice day da',
 'anything lor',
 'ha u e thing got tv watch u thk go tonight u already haf smth mind',
 'jos ask u wana meet',
 'describe lucky actually awake noon',
 'hey loverboy love tell look picture ache feel leg fuck want need crave',
 'yeah leave hour least sound',
 'surfing online store offer want buy thing',
 'sunshine quiz win super sony dvd recorder canname capital australia text mquiz b',
 'come lt n pas lar',
 'reach office around lt decimal gt amp mobile problem cann get voice call asa free',
 'r going today meeting',
 'back amp packing car let know room',
 'eh den sat u book e kb liao huh',
 'way office da',
 'dont make ne plan nxt wknd coz want u come ok',
 'hand phone chat wit u',
 'dating two started sent text talk sport radio last week connection think coincidence',
 'home',
 'oh really make air talent',
 'noe da car later c lar wearing short',
 'another month need chocolate weed alcohol',
 'well leave class babe never came back hope nice sleep love',
 'rude campus',
 'good afternoon babe go day job prospect yet miss love sigh',
 'er hello thing quite go plan limping slowly home followed aa exhaust hanging',
 'haf msn yijue hotmail com',
 'reached home tired come tomorro',
 'mmmmm sooooo good wake word morning love mmmm fuck love lion devouring kiss across sea',
 'k send lt gt min',
 'new message call',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',

In [64]:
len(X_train),len(y_train)

(4457, 4457)

In [65]:
# create BOW 
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [66]:
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [67]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [68]:
from sklearn.naive_bayes import MultinomialNB
spmamodel=MultinomialNB().fit(X_train,y_train)

In [69]:
spmamodel

MultinomialNB()

In [70]:
y_pred=spmamodel.predict(X_test)

In [71]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
classification_report(y_test,y_pred)
confusion_m=confusion_matrix(y_test,y_pred)
accuracy=accuracy_score(y_test,y_pred)
print(confusion_m)
print(accuracy)
print(classification_report(y_test,y_pred))

[[136  11]
 [ 12 956]]
0.979372197309417
              precision    recall  f1-score   support

         0.0       0.92      0.93      0.92       147
         1.0       0.99      0.99      0.99       968

    accuracy                           0.98      1115
   macro avg       0.95      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115

In [22]:
# test with new messages
#from textpreprocessing import preprocess_text
new_messages = ["Congratulations! You've won a free iPhone!", "Hey, are we still on for lunch tomorrow?"]
new_corpus=[]
for i in range(0,len(new_messages)):
    review=re.sub('[^a-zA-Z]',' ',new_messages[i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    new_corpus.append(review)

In [ ]:
#test cleaning and preprocessing
# convert to vector using the same CountVectorizer
new_vectors = cv.transform(new_corpus).toarray()
new_vectors
y_pred = spmamodel.predict(new_vectors)
y_pred
# compare the predictions with the actual labels

array([0., 1.])

# TF-IDF

In [105]:
#train test split 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [106]:
X_train

['reach ur home lt gt minute',
 'playin space poker u',
 'wait come lt gt min',
 'yes please leave lt gt lt gt leave',
 'yeah whatever lol',
 'aiyah wait lor u entertain hee',
 'k need login anything',
 'ur face test lt gt select number tell ur face astrology waiting quick reply',
 'yes obviously egg pert potato head speak soon',
 'late k wish',
 'pls confirm time collect cheque',
 'movie call wat',
 'urgent trying contact u today draw show prize guaranteed call land line claim valid hr',
 'tomarrow want got court lt decimal gt come bus stand',
 'home watching tv lor',
 'stuck da middle da row da right hand side da lt',
 'nice line said broken heart plz cum time infront wise trust u good',
 'cool tyler take gonna buy drop place later tonight total order quarter got enough',
 'hi roger cl',
 'ok lor msg b u call',
 'thing r good thanx got exam march ive done revision fran still boyf ive gotta interviw exeter bit worried x',
 'mths half price orange line rental latest camera phone free phone mths call mobilesdirect free update stoptxt',
 'told coming wednesday',
 'u secret admirer looking make contact u find r reveal think ur special call',
 'emailed yifeng part oredi get fr',
 'likely called mittelschmertz google dont paracetamol dont worry go',
 'everybody fun evening miss',
 'sorry grocer',
 'actually fuck whatever find excuse tampa point january though',
 'funny fact nobody teach volcano erupt tsunami arise hurricane sway aroundn teach hw choose wife natural disaster happens',
 'misplaced number sending text old number wondering heard year best mcat got number atlanta friend',
 'know god created gap finger one made come amp fill gap holding hand love',
 'never lei v lazy got wat dat day send da url cant work one',
 'coming friday leave pongal get news work place',
 'haha dont angry take practice real thing',
 'chosen receive award pls call claim number collect award selected receive valued mobile customer',
 'thank u better work cause feel used otherwise',
 'b going sch mon si need take smth',
 'haha yup hopefully lose kg mon hip hop go orchard weigh',
 'look amy ure beautiful intelligent woman like u lot know u like like worry',
 'hey check da listed da',
 'u going ikea str aft dat',
 'meant apology texting get drug lt gt night',
 'yo call get chance friend mine wanted ask big order',
 'lol gonna last month cashed left lt gt case collecting week cause announced blog',
 'sorry call later',
 'geeeee internet really bad today eh',
 'happen dear tell',
 'ur paper',
 'oh send address',
 'people see msg think iam addicted msging wrong bcoz know iam addicted sweet friend bslvyl',
 'free text msg text ok credit account',
 'dude got haircut breezy',
 'please call customer service representative freephone pm guaranteed cash prize',
 'hey sexy bun told adore loverboy hope remember thank sister law meatball grin love babe',
 'oh sorry please',
 'yes princess want make happy',
 'attended nothing',
 'call later network urgnt sm',
 'gonna ask lol think',
 'worry though understand important put place poorly thought punishment face worst thing ever happened brb gonna go kill',
 'know dat feelin pete wuld get em nuther place nuther time mayb',
 'yes tv always available work place',
 'hi baby im sat bloody bus mo wont home wanna somethin later call later ortxt back jess xx',
 'convey regard',
 'message text missing sender name missing number missing sent date missing missing u lot thats everything missing sent via fullonsms com',
 'anytime',
 'latest g still scrounge ammo want give new ak try',
 'ah well confuses thing',
 'one issue california okay snow manageable',
 'neft transaction reference number lt gt r lt decimal gt credited beneficiary account lt gt lt time gt lt gt',
 'haha get used driving usf man know lot stoner',
 'u secret admirer looking make contact u find r reveal think ur special call',
 'yes meet town co go gep home could text bus stop worry finished march ish',
 'tell female v throwing deciding get',
 'break time one come n get stuff fr',
 'yes come nyc audiitions trying relocate',
 'lol u trust',
 'standing',
 'chance reality fantasy show call p per min ntt ltd po box croydon cr wb national rate call',
 'like think always possibility pub later',
 'dude ive seeing lotta corvette lately',
 'hey sweet wondering moment might come want send file someone go yahoo connection suck remember set page go download format disc could tell know way download big file download stuff directly internet help would great prey teasing kiss',
 'u sick still go shopping',
 'new textbuddy chat horny guy ur area p free receive search postcode gaytextbuddy com txt one name rpl stop cnl',
 'plz tell an bslvyl sent via fullonsms com',
 'waiting call sir',
 'also know lunch menu da know',
 'bring got',
 'fffff text kadeem far gone',
 'well must pain catch',
 'co darren say considering mah ask',
 'alrite jod hows revision goin keris bin doin smidgin n e way u wanna cum college xx',
 'link picture sent also use http alto co uk wave wave asp',
 'age abj',
 'nan sonathaya soladha bos',
 'nah help never iphone',
 'quite ok bit ex u better go eat smth else feel guilty',
 'thanks yesterday sir wonderful hope enjoyed burial mojibiola',
 'dear angry busy dear',
 'much getting',
 'thanks sending mental ability question',
 'k yan jiu liao sat go bugis vill one frm den hop parco nb sun go cine frm den hop orc mrt hip hop',
 'wanna watch movie',
 'yep get program slacking',
 'printed oh lt gt come upstairs',
 'machan go gym tomorrow wil come late goodnight',
 'number gonna massive pain as rather get involved possible',
 'u call lunch',
 'em olowoyey usc edu great time argentina sad secretary everything blessing',
 'er yep sure prop',
 'avatar supposed subtoitles',
 'hey babe u doin wot u nite love annie x',
 'somewhere beneath pale moon light someone think u dream come true goodnite amp sweet dream',
 'watching tv got new job',
 'hi ur lookin saucy daytime fun wiv busty married woman free next week chat sort time janinexx call minmobsmorelkpobox hp fl',
 'think fixed send test message',
 'ill obey',
 'good day',
 'worry sure get',
 'new theory argument win situation loses person dont argue ur friend kick amp say always correct',
 'hahaha use brain dear',
 'outside island head towards hard rock run',
 'leaving house',
 'want kfc tuesday buy meal gravy mark',
 'b going esplanade fr home',
 'came hostel going sleep plz call class hrishi',
 'bloody hell cant believe forgot surname mr ill give u clue spanish begin',
 'hate call didnt accept even single call mine even messaged',
 'operate lt gt',
 'please sen kind advice please come try',
 'get ready moan scream',
 'lay man let know missed thought great day send bimbo ugo number ill appreciate safe',
 'interflora late order interflora flower christmas call place order midnight tomorrow',
 'rushing working school rush go hungry',
 'well great weekend',
 'great day beautiful one',
 'k see k',
 'way transport less problematic sat night way u want ask n join bday feel free need know definite no booking fri',
 'remains bro amongst bros',
 'sorry chikku cell got problem thts nt able reply u msg u',
 'catch bus frying egg make tea eating mom left dinner feel love',
 'rat hey u ever vote next theme',
 'kallis wont play first two odi',
 'hey going quit soon xuhui working till end month',
 'e timing go w u lor',
 'paying attention',
 'ask dad pick lar wan stay meh',
 'tell something thats okay',
 'need drug anymore',
 'spoil bed well',
 'yeah tote u wanna',
 'got ur favorite oyster n got favorite sashimi ok lar dun say already wait ur stomach start rumbling',
 'smile pleasure smile pain smile trouble pours like rain smile sum hurt u smile becoz someone still love see u smiling',
 'several sir',
 'tell quite long co finish film yet',
 'sir late paying rent past month pay lt gt charge felt would inconsiderate nag something give great cost didnt speak however recession wont able pay charge month hence askin well ahead month end please help thanks',
 'yeah gang ready',
 'yo yo yo byatch whassup',
 'neva tell noe home da aft wat',
 'yay wait party together',
 'sent ur email id soon',
 'tell make little spreadsheet track whose idea smoke determine smoke much entire month february come',
 'home lei',
 'k jason say gonna around around lt gt',
 'emigrated something ok maybe bit hopeful',
 'see requirement please',
 'eldest know',
 'good day mine really busy much tomorrow night',
 'career tel added u contact indyarocks com send free sm remove phonebook sm lt gt',
 'well glad find totally disagreeable lol',
 'babe hope ok shit night sleep fell asleep knackered dreading work tonight thou upto tonight x',
 'please tell car key purse',
 'hurt tease make cry end life die plz keep one rose grave say stupid miss u nice day bslvyl',
 'hello news job making wait fifth week yeah im woozles weasel exeter still home',
 'aah cuddle would lush need lot tea soup kind fumbling',
 'told going got drunk',
 'like cheap happy splash wine make feel better',
 'shopping lor raining mah hard leave orchard',
 'geeee miss already know think fuck wait till next year together loving kiss',
 'ok thk got u wan come wat',
 'never try alone take weight tear come ur heart fall ur eye always remember stupid friend share bslvyl',
 'nvm take ur time',
 'shit surprised went spent evening french guy met town fooled around bit let fuck',
 'darren saying dat u meeting da ge den dun meet dinner co later u leave xy feel awkward den u meet lunch lor',
 'forgot take year shower sorry phone dead yet',
 'cab available pick drop door step',
 'together thinkin',
 'think steyn surely get one wicket',
 'oh get paid outstanding one commercial hasbro august made u jump many hoop get paid still',
 'depends quality want type sent boye faded glory want ralphs maybe',
 'many people seems special first sight remain special till last sight maintain till life end sh jas',
 'mean get door',
 'k wen ur free come home also tel vikky hav sent mail also better come evening il free today aftr pm',
 'yeah leave couple minute amp let know get mu',
 'babe lost try rebooting',
 'hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk got lo oso forgot liao',
 'ok anybody asks abt u tel p',
 'oh howda gud gud mathe en samachara chikku',
 'take u shopping mark distract isaiah',
 'dear call',
 'screaming mean shouting',
 'hey da cool iknow wellda peril studentfinancial crisis spk u l r',
 'uncle boye need movie oh guide plus know torrent particularly legal system slowing gr day plus started co dont meet online honey moon',
 'comingdown later',
 'im sorry bout last nite ur fault spouse pmt sumthin u give think u shldxxxx',
 'hey glad u r better hear u treated urself digi cam good r pm fab new year c u coupla wks',
 'take care n get well soon',
 'mean u could keep ur word',
 'evo download flash jealous',
 'xmas iscoming ur awarded either cd gift voucher free entry r weekly draw txt music tnc www ldew com win ppmx age subscription',
 'good morning plz call sir',
 'trying reach without success',
 'u know watchin lido',
 'designation software developer may get chennai',
 'sorry able get see morning',
 'cud u tell ppl im gona b bit l co bus hav gon past co full im still waitin pete x',
 'found enc lt gt',
 'aight lemme know',
 'wait lt gt min',
 'actually sleeping still might u call back text gr rock si send u text wen wake',
 'dont file bag work called tell find anything room',
 'wont get concentration dear know mind everything',
 'said anything wrong sorry de',
 'borrow ur bag ok',
 'thanks bomb date phone wanted say',
 'yes chatting',
 'call say coming today ok tell fool like ok',
 'answerin phone actually pretty reasonable hour sleepy',
 'buy space invader chance win orig arcade game console press game arcade std wap charge see co uk game term setting purchase',
 'aight set free think could text blake address occurs quite sure thought',
 'ok every night take warm bath drink cup milk see work magic still need loose weight know',
 'text meet someone sexy today u find date even flirt u join p reply name age eg sam msg recd thirtyeight penny',
 'free st week nokia tone ur mob every week txt nokia get txting tell ur mate www getzed co uk pobox w wq norm p tone',
 'shall call dear food',
 'dear free message without recharge hi hi hi',
 'right make appointment right',
 'ok anyway need change said',
 'r meeting',
 'aathi dear',
 'lovely night xxx',
 'need detail online job',
 'win year supply cd store ur choice worth enter weekly draw txt music t c www ldew com sub win ppmx',
 'download many ringtones u like restriction choose u even send yr buddy txt sir',
 'rock yr chik get filthy film xxx pic yr phone rply filth saristar ltd e yt p per day stop cancel',
 'wait cornwall hope tonight bad well rock night shite anyway going kip good night speak soon',
 'hard believe thing like say lie think twice saying anything',
 'mobile mths update latest orange camera video phone free save free text weekend call text yes callback orno opt',
 'yup izzit still raining heavily co e mrt c outside',
 'working ringing u thing whole houseful screaming brat pulling hair loving u',
 'give something drink take vomit temp might drop unmits however let know',
 'ur cash balance currently pound maximize ur cash send go p msg cc po box tcr w',
 'email alertfrom jeri stewartsize kbsubject low cost prescripiton drvgsto listen email call',
 'like spoiled',
 'sorry man account dry would want could trade back half could buy shit credit card',
 'baby promise treat well bet take good care',
 'huh early dinner outside izzit',
 'r home come within min',
 'ok',
 'urgent mobile number awarded prize guaranteed call land line claim valid hr ppm',
 'rounder required',
 'sorry free',
 'fret buy ovulation test strip send wont get til like march send postal address u alright okay',
 'send email mind lt gt time per night',
 'plz note anyone calling mobile co amp asks u type lt gt lt gt disconnect call coz iz attempt terrorist make use sim card itz confirmd nokia n motorola n verified cnn ibn',
 'cbe chennai',
 'wnt buy bmw car urgently vry urgent hv shortage lt gt lac source arng dis amt lt gt lac thats prob',
 'heard u call night knickers make beg like u last time xx luv nikiyu net',
 'nothing meant money enters account bank remove flat rate someone transfered lt gt account lt gt dollar got removed bank differ charge also differ sure trust ja person sending account detail co',
 'said look pretty wif long hair wat thk cutting quite short leh',
 'since side fever vomitin',
 'going film day da pm sorry da',
 'leave around four ok',
 'probs hon u doinat mo',
 'hi test lt gt rd',
 'r u continent',
 'loan purpose homeowner tenant welcome previously refused still help call free text back help',
 'stopped get ice cream go back',
 'actually getting ready leave house',
 'date sunday',
 'always putting business put picture as facebook one open people ever met would think picture room would hurt make feel violated',
 'b floppy b snappy happy gay chat service photo upload call p min stop text call',
 'want lt gt r da',
 'pls ask macho much budget bb bold co saw new one lt gt dollar',
 'tell thinking plus going stop run',
 'carlos pick swing usf little bit',
 'sorry trouble u buy dad big small sat n sun thanx',
 'okie',
 'went ur hon lab one',
 'tough',
 'lol would mom would fit tell whole family crazy terrible',
 'raji pls favour pls convey birthday wish nimya pls today birthday',
 'yo know anyone lt gt otherwise able buy liquor guy flaked right get hold somebody loko night',
 'smile pleasure smile pain smile trouble pours like rain smile sum hurt u smile becoz someone still love see u smiling',
 'message sent askin lt gt dollar shoul pay lt gt lt gt',
 'feel like trying kadeem v',
 'theoretically yeah could able come',
 'congrats nokia video camera phone call call cost ppm ave call min vary mobile close post bcm ldn wc n xx',
 'sorry call later',
 'ok cool see ya',
 'lol grr mom taking forever prescription pharmacy like minute away ugh',
 'get gift year didnt get anything bad',
 'seen back holby',
 'wats ur opinion abt abt character',
 'time want come',
 'stomach thru much trauma swear eat better lose weight',
 'tmr brin lar aiya later come n c lar mayb neva set properly got da help sheet wif',
 'urgent please call landline complimentary lux costa del sol holiday cash await collection ppm sae c james eh rr',
 'call use ur min call cast p min mob vary service provided aom gbp month aom box er u stop age',
 'telling coulda real valentine u never pick nothing',
 'notice like looking shit mirror youre turning right freak',
 'really crashed cuddled sofa',
 'mean post wrote like many time ritten stuff let sit feeling time angry left hit send stop checked phone got car said sleep bored time clean fold laundry etc least make bed',
 'cheer message zogtorius staring phone age deciding whether text',
 'goodnight da thangam really miss u dear',
 'wah okie okie muz make use e unlimited haha',
 'haha friend tyler literally asked could get dubsack',
 'nice pub near frankie n benny near warner cinema',
 'shall book chez jules half eight ok',
 'da vijay going talk jaya tv',
 'thanx today cer nice catch ave find time often oh well take care c u soon c',
 'hi darlin hope nice night wish come cant wait see love fran p want dirty anal sex want man gang bang',
 'let ur heart ur compass ur mind ur map ur soul ur guide u never loose world gnun sent via way sm com',
 'today iz yellow rose day u love frndship give misscall amp send ur frndz amp see many miss call u get u get missed u marry ur lover',
 'love cuddle want hold strong arm right',
 'think mentor percent sure',
 'sorry missed babe late slept hope enjoy driving lesson boytoy miss teasing kiss',
 'princess bet brothas chasing',
 'aight tomorrow around lt gt',
 'also andros ice etc etc',
 'studying free next weekend',
 'u get pic msg phone',
 'told dr appt next week think gonna die told check nothing worried listen',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'aight thanks comin',
 'hi baby im cruisin girl friend r u give call hour home thats alright fone fone love jenny xxx',
 'imagine finally get sink bath put pace maybe even eat left also imagine feel cage cock surrounded bath water reminding always owns enjoy cuck',
 'near kalainar tv office thenampet',
 'go e normal pilate intro',
 'call meet',
 'si lor juz watched italian job',
 'pls full name joke school co fee university florida seem actually lt gt k pls holla back',
 'taxt massage tie po argh ok lool',
 'good afternoon boytoy go walking day get police abstract still wake miss babe',
 'greatest test courage earth bear defeat without losing heart gn tc',
 'sent like',
 'famous quote develop ability listen anything unconditionally without losing temper self confidence mean married',
 'lmao nice',
 'guaranteed cash prize claim yr prize call customer service representative pm cost p',
 'thought king hill thing',
 'friend use call',
 'wat r u',
 'yeah try scrounge something',
 'kallis dismissial nd test',
 'k k detail want transfer acc enough',
 'sun ah thk mayb dun anythin thk book e lesson e pilate orchard mrt u noe hor',
 'miss much desparate recorded message left day listen hear sound voice love',
 'saturday sunday holiday difficult',
 'ok come ur home half hour',
 'people game mall iouri kaila',
 'k actually guy meet sunoco howard right way',
 'get class bsn like lt gt minute know advising',
 'pls send comprehensive mail paying much',
 'released vday shirt u put make bottom half naked instead white underwear',
 'replying boye changed phone number',
 'told tell stupid hear wont tell anything dad called brother spoken',
 'lol forgot eh yes bring babe',
 'know shall speak lt gt minute',
 'try get lost fact tee hee',
 'thinking lifting one',
 'great trip india bring light everyone project everyone lucky see smile bye abiola',

In [107]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=2500, ngram_range=(1,3))
X_train = tfidf.fit_transform(X_train)
X_test = tfidf.transform(X_test)

In [108]:
tfidf.vocabulary_

{'reach': np.int64(1656),
 'ur': np.int64(2258),
 'home': np.int64(934),
 'lt': np.int64(1180),
 'gt': np.int64(824),
 'minute': np.int64(1294),
 'ur home': np.int64(2270),
 'lt gt': np.int64(1183),
 'gt minute': np.int64(832),
 'lt gt minute': np.int64(1190),
 'space': np.int64(1918),
 'wait': np.int64(2350),
 'come': np.int64(386),
 'min': np.int64(1281),
 'gt min': np.int64(831),
 'lt gt min': np.int64(1189),
 'yes': np.int64(2483),
 'please': np.int64(1535),
 'leave': np.int64(1093),
 'gt lt': np.int64(829),
 'lt gt lt': np.int64(1188),
 'gt lt gt': np.int64(830),
 'yeah': np.int64(2480),
 'whatever': np.int64(2406),
 'lol': np.int64(1140),
 'aiyah': np.int64(32),
 'lor': np.int64(1154),
 'hee': np.int64(893),
 'need': np.int64(1390),
 'login': np.int64(1137),
 'anything': np.int64(65),
 'face': np.int64(622),
 'test': np.int64(2058),
 'number': np.int64(1435),
 'tell': np.int64(2046),
 'waiting': np.int64(2352),
 'quick': np.int64(1631),
 'reply': np.int64(1702),
 'tell ur': np.int64(2048),
 'obviously': np.int64(1445),
 'egg': np.int64(571),
 'head': np.int64(884),
 'speak': np.int64(1919),
 'soon': np.int64(1908),
 'speak soon': np.int64(1922),
 'late': np.int64(1075),
 'wish': np.int64(2424),
 'pls': np.int64(1541),
 'confirm': np.int64(411),
 'time': np.int64(2119),
 'collect': np.int64(372),
 'movie': np.int64(1353),
 'call': np.int64(223),
 'wat': np.int64(2372),
 'urgent': np.int64(2301),
 'trying': np.int64(2194),
 'contact': np.int64(418),
 'today': np.int64(2141),
 'draw': np.int64(541),
 'show': np.int64(1847),
 'prize': np.int64(1599),
 'guaranteed': np.int64(836),
 'land': np.int64(1061),
 'line': np.int64(1120),
 'claim': np.int64(339),
 'valid': np.int64(2325),
 'hr': np.int64(959),
 'urgent trying': np.int64(2313),
 'trying contact': np.int64(2195),
 'contact today': np.int64(422),
 'today draw': np.int64(2143),
 'draw show': np.int64(544),
 'show prize': np.int64(1848),
 'prize guaranteed': np.int64(1606),
 'guaranteed call': np.int64(837),
 'call land': np.int64(239),
 'land line': np.int64(1062),
 'line claim': np.int64(1121),
 'claim valid': np.int64(349),
 'valid hr': np.int64(2326),
 'urgent trying contact': np.int64(2314),
 'trying contact today': np.int64(2196),
 'contact today draw': np.int64(423),
 'today draw show': np.int64(2144),
 'draw show prize': np.int64(545),
 'show prize guaranteed': np.int64(1849),
 'prize guaranteed call': np.int64(1607),
 'guaranteed call land': np.int64(838),
 'call land line': np.int64(240),
 'land line claim': np.int64(1063),
 'line claim valid': np.int64(1122),
 'claim valid hr': np.int64(350),
 'want': np.int64(2362),
 'got': np.int64(802),
 'decimal': np.int64(490),
 'bus': np.int64(211),
 'stand': np.int64(1939),
 'lt decimal': np.int64(1181),
 'decimal gt': np.int64(491),
 'lt decimal gt': np.int64(1182),
 'watching': np.int64(2376),
 'tv': np.int64(2203),
 'watching tv': np.int64(2377),
 'da': np.int64(466),
 'row': np.int64(1747),
 'right': np.int64(1728),
 'hand': np.int64(865),
 'side': np.int64(1857),
 'nice': np.int64(1406),
 'said': np.int64(1761),
 'heart': np.int64(887),
 'plz': np.int64(1549),
 'cum': np.int64(456),
 'trust': np.int64(2189),
 'good': np.int64(785),
 'cool': np.int64(428),
 'tyler': np.int64(2226),
 'take': np.int64(2021),
 'gonna': np.int64(783),
 'buy': np.int64(214),
 'drop': np.int64(552),
 'place': np.int64(1527),
 'later': np.int64(1076),
 'tonight': np.int64(2161),
 'total': np.int64(2169),
 'order': np.int64(1476),
 'enough': np.int64(587),
 'later tonight': np.int64(1078),
 'got enough': np.int64(803),
 'hi': np.int64(905),
 'roger': np.int64(1739),
 'ok': np.int64(1452),
 'msg': np.int64(1359),
 'ok lor': np.int64(1453),
 'thing': np.int64(2091),
 'thanx': np.int64(2085),
 'exam': np.int64(614),
 'march': np.int64(1229),
 'ive': np.int64(1024),
 'done': np.int64(532),
 'still': np.int64(1957),
 'gotta': np.int64(809),
 'bit': np.int64(178),
 'worried': np.int64(2448),
 'mths': np.int64(1361),
 'half': np.int64(860),
 'price': np.int64(1589),
 'orange': np.int64(1474),
 'rental': np.int64(1697),
 'latest': np.int64(1079),
 'camera': np.int64(273),
 'phone': np.int64(1509),
 'free': np.int64(676),
 'update': np.int64(2252),
 'stoptxt': np.int64(1974),
 'half price': np.int64(862),
 'price orange': np.int64(1592),
 'line rental': np.int64(1123),
 'latest camera': np.int64(1080),
 'camera phone': np.int64(277),
 'phone free': np.int64(1510),
 'free phone': np.int64(684),
 'half price orange': np.int64(864),
 'price orange line': np.int64(1593),
 'camera phone free': np.int64(278),
 'told': np.int64(2150),
 'coming': np.int64(394),
 'wednesday': np.int64(2386),
 'secret': np.int64(1789),
 'admirer': np.int64(15),
 'looking': np.int64(1151),
 'make': np.int64(1215),
 'find': np.int64(649),
 'reveal': np.int64(1722),
 'think': np.int64(2092),
 'special': np.int64(1923),
 'secret admirer': np.int64(1790),
 'admirer looking': np.int64(16),
 'looking make': np.int64(1152),
 'make contact': np.int64(1216),
 'contact find': np.int64(420),
 'find reveal': np.int64(651),
 'reveal think': np.int64(1723),
 'think ur': np.int64(2096),
 'ur special': np.int64(2292),
 'special call': np.int64(1924),
 'secret admirer looking': np.int64(1791),
 'admirer looking make': np.int64(17),
 'looking make contact': np.int64(1153),
 'make contact find': np.int64(1217),
 'contact find reveal': np.int64(421),
 'find reveal think': np.int64(652),
 'reveal think ur': np.int64(1724),
 'think ur special': np.int64(2097),
 'ur special call': np.int64(2293),
 'part': np.int64(1489),
 'oredi': np.int64(1477),
 'get': np.int64(731),
 'fr': np.int64(675),
 'called': np.int64(263),
 'google': np.int64(801),
 'dont': np.int64(533),
 'worry': np.int64(2449),
 'go': np.int64(761),
 'fun': np.int64(710),
 'evening': np.int64(604),
 'miss': np.int64(1298),
 'sorry': np.int64(1909),
 'actually': np.int64(11),
 'fuck': np.int64(705),
 'excuse': np.int64(617),
 'tampa': np.int64(2032),
 'point': np.int64(1564),
 'january': np.int64(1025),
 'though': np.int64(2103),
 'funny': np.int64(711),
 'fact': np.int64(624),
 'nobody': np.int64(1412),
 'teach': np.int64(2039),
 'hw': np.int64(972),
 'choose': np.int64(334),
 'wife': np.int64(2414),
 'happens': np.int64(874),
 'sending': np.int64(1820),
 'text': np.int64(2059),
 'old': np.int64(1459),
 'wondering': np.int64(2441),
 'heard': np.int64(886),
 'year': np.int64(2481),
 'best': np.int64(164),
 'friend': np.int64(695),
 'know': np.int64(1056),
 'god': np.int64(771),
 'created': np.int64(449),
 'gap': np.int64(716),
 'finger': np.int64(654),
 'one': np.int64(1461),
 'made': np.int64(1209),
 'amp': np.int64(45),
 'fill': np.int64(645),
 'holding': np.int64(926),
 'love': np.int64(1165),
 'god created': np.int64(772),
 'gap holding': np.int64(717),
 'god created gap': np.int64(773),
 'never': np.int64(1395),
 'lei': np.int64(1098),
 'lazy': np.int64(1086),
 'dat': np.int64(473),
 'day': np.int64(477),
 'send': np.int64(1811),
 'cant': np.int64(282),
 'work': np.int64(2444),
 'day send': np.int64(481),
 'friday': np.int64(694),
 'pongal': np.int64(1570),
 'news': np.int64(1402),
 'haha': np.int64(857),
 'angry': np.int64(50),
 'practice': np.int64(1583),
 'real': np.int64(1668),
 'receive': np.int64(1675),
 'award': np.int64(119),
 'selected': np.int64(1801),
 'valued': np.int64(2328),
 'mobile': np.int64(1313),
 'customer': np.int64(460),
 'receive award': np.int64(1676),
 'pls call': np.int64(1542),
 'call claim': np.int64(228),
 'selected receive': np.int64(1802),
 'thank': np.int64(2080),
 'better': np.int64(167),
 'cause': np.int64(306),
 'feel': np.int64(637),
 'used': np.int64(2317),
 'otherwise': np.int64(1480),
 'going': np.int64(776),
 'sch': np.int64(1778),
 'mon': np.int64(1337),
 'si': np.int64(1855),
 'smth': np.int64(1893),
 'going sch': np.int64(779),
 'yup': np.int64(2498),
 'hopefully': np.int64(943),
 'lose': np.int64(1158),
 'hip': np.int64(913),
 'hop': np.int64(937),
 'orchard': np.int64(1475),
 'hip hop': np.int64(914),
 'look': np.int64(1147),
 'beautiful': np.int64(152),
 'woman': np.int64(2438),
 'like': np.int64(1114),
 'lot': np.int64(1161),
 'hey': np.int64(900),
 'check': np.int64(325),
 'str': np.int64(1977),
 'aft': np.int64(21),
 'meant': np.int64(1254),
 'texting': np.int64(2070),
 'drug': np.int64(554),
 'night': np.int64(1408),
 'yo': np.int64(2492),
 'chance': np.int64(313),
 'mine': np.int64(1293),
 'wanted': np.int64(2369),
 'ask': np.int64(97),
 'big': np.int64(170),
 'call get': np.int64(234),
 'last': np.int64(1072),
 'month': np.int64(1340),
 'left': np.int64(1096),
 'case': np.int64(296),
 'week': np.int64(2388),
 'sorry call': np.int64(1910),
 'call later': np.int64(243),
 'sorry call later': np.int64(1911),
 'internet': np.int64(1008),
 'really': np.int64(1669),
 'bad': np.int64(132),
 'eh': np.int64(572),
 'happen': np.int64(870),
 'dear': np.int64(485),
 'paper': np.int64(1486),
 'ur paper': np.int64(2285),
 'oh': np.int64(1449),
 'address': np.int64(14),
 'people': np.int64(1497),
 'see': np.int64(1793),
 'iam': np.int64(973),
 'wrong': np.int64(2461),
 'bcoz': np.int64(147),
 'sweet': np.int64(2015),
 'bslvyl': np.int64(205),
 'iam addicted': np.int64(974),
 'credit': np.int64(450),
 'account': np.int64(6),
 'free text': np.int64(687),
 'dude': np.int64(555),
 'service': np.int64(1831),
 'representative': np.int64(1711),
 'freephone': np.int64(690),
 'pm': np.int64(1550),
 'cash': np.int64(297),
 'please call': np.int64(1536),
 'call customer': np.int64(230),
 'customer service': np.int64(461),
 'service representative': np.int64(1832),
 'pm guaranteed': np.int64(1552),
 'guaranteed cash': np.int64(839),
 'cash prize': np.int64(302),
 'please call customer': np.int64(1537),
 'call customer service': np.int64(231),
 'customer service representative': np.int64(462),
 'pm guaranteed cash': np.int64(1553),
 'guaranteed cash prize': np.int64(840),
 'sexy': np.int64(1837),
 'loverboy': np.int64(1177),
 'hope': np.int64(938),
 'remember': np.int64(1694),
 'sister': np.int64(1872),
 'law': np.int64(1085),
 'grin': np.int64(821),
 'babe': np.int64(129),
 'princess': np.int64(1594),
 'happy': np.int64(876),
 'princess want': np.int64(1595),
 'nothing': np.int64(1429),
 'network': np.int64(1392),
 'sm': np.int64(1887),
 'understand': np.int64(2240),
 'important': np.int64(991),
 'put': np.int64(1624),
 'thought': np.int64(2104),
 'ever': np.int64(605),
 'happened': np.int64(872),
 'pete': np.int64(1508),
 'em': np.int64(575),
 'mayb': np.int64(1249),
 'always': np.int64(42),
 'available': np.int64(111),
 'baby': np.int64(130),
 'im': np.int64(984),
 'sat': np.int64(1767),
 'mo': np.int64(1309),
 'wont': np.int64(2442),
 'wanna': np.int64(2361),
 'back': np.int64(131),
 'xx': np.int64(2473),
 'convey': np.int64(425),
 'regard': np.int64(1688),
 'message': np.int64(1272),
 'missing': np.int64(1305),
 'name': np.int64(1377),
 'sent': np.int64(1822),
 'date': np.int64(474),
 'thats': np.int64(2086),
 'everything': np.int64(612),
 'via': np.int64(2330),
 'fullonsms': np.int64(708),
 'com': np.int64(382),
 'sent via': np.int64(1824),
 'fullonsms com': np.int64(709),
 'anytime': np.int64(67),
 'give': np.int64(752),
 'new': np.int64(1396),
 'try': np.int64(2193),
 'ah': np.int64(26),
 'well': np.int64(2400),
 'issue': np.int64(1022),
 'okay': np.int64(1457),
 'snow': np.int64(1894),
 'transaction': np.int64(2178),
 'reference': np.int64(1686),
 'reference number': np.int64(1687),
 'lt time': np.int64(1194),
 'time gt': np.int64(2122),
 'lt time gt': np.int64(1195),
 'driving': np.int64(551),
 'usf': np.int64(2319),
 'man': np.int64(1222),
 'meet': np.int64(1258),
 'town': np.int64(2174),
 'co': np.int64(362),
 'could': np.int64(439),
 'stop': np.int64(1963),
 'finished': np.int64(656),
 'ish': np.int64(1019),
 'bus stop': np.int64(212),
 'break': np.int64(201),
 'stuff': np.int64(1984),
 'come get': np.int64(388),
 'fantasy': np.int64(629),
 'per': np.int64(1498),
 'ntt': np.int64(1431),
 'ltd': np.int64(1196),
 'po': np.int64(1556),
 'box': np.int64(196),
 'croydon': np.int64(451),
 'cr': np.int64(445),
 'wb': np.int64(2381),
 'national': np.int64(1378),
 'rate': np.int64(1646),
 'call per': np.int64(251),
 'per min': np.int64(1499),
 'min ntt': np.int64(1284),
 'ntt ltd': np.int64(1432),
 'ltd po': np.int64(1197),
 'po box': np.int64(1557),
 'box croydon': np.int64(197),
 'croydon cr': np.int64(452),
 'cr wb': np.int64(446),
 'national rate': np.int64(1379),
 'rate call': np.int64(1649),
 'call per min': np.int64(252),
 'per min ntt': np.int64(1500),
 'min ntt ltd': np.int64(1285),
 'ntt ltd po': np.int64(1433),
 'ltd po box': np.int64(1198),
 'po box croydon': np.int64(1558),
 'box croydon cr': np.int64(198),
 'croydon cr wb': np.int64(453),
 'national rate call': np.int64(1380),
 'pub': np.int64(1619),
 'seeing': np.int64(1798),
 'moment': np.int64(1336),
 'might': np.int64(1277),
 'file': np.int64(644),
 'someone': np.int64(1900),
 'yahoo': np.int64(2477),
 'suck': np.int64(1993),
 'set': np.int64(1834),
 'page': np.int64(1484),
 'download': np.int64(540),
 'way': np.int64(2380),
 'directly': np.int64(518),
 'help': np.int64(898),
 'would': np.int64(2455),
 'great': np.int64(816),
 'teasing': np.int64(2042),
 'kiss': np.int64(1052),
 'might come': np.int64(1278),
 'teasing kiss': np.int64(2043),
 'sick': np.int64(1856),
 'shopping': np.int64(1844),
 'chat': np.int64(323),
 'horny': np.int64(945),
 'guy': np.int64(851),
 'area': np.int64(83),
 'search': np.int64(1784),
 'txt': np.int64(2206),
 'an': np.int64(49),
 'sir': np.int64(1870),
 'waiting call': np.int64(2353),
 'call sir': np.int64(257),
 'also': np.int64(41),
 'lunch': np.int64(1203),
 'menu': np.int64(1269),
 'bring': np.int64(202),
 'far': np.int64(630),
 'gone': np.int64(782),
 'must': np.int64(1373),
 'pain': np.int64(1485),
 'catch': np.int64(305),
 'darren': np.int64(472),
 'say': np.int64(1774),
 'mah': np.int64(1211),
 'alrite': np.int64(40),
 'hows': np.int64(955),
 'goin': np.int64(775),
 'bin': np.int64(173),
 'doin': np.int64(530),
 'college': np.int64(378),
 'link': np.int64(1124),
 'picture': np.int64(1520),
 'use': np.int64(2316),
 'http': np.int64(961),
 'uk': np.int64(2231),
 'co uk': np.int64(364),
 'age': np.int64(24),
 'bos': np.int64(193),
 'nah': np.int64(1376),
 'quite': np.int64(1633),
 'ex': np.int64(613),
 'eat': np.int64(567),
 'else': np.int64(574),
 'thanks': np.int64(2081),
 'yesterday': np.int64(2489),
 'wonderful': np.int64(2440),
 'busy': np.int64(213),
 'much': np.int64(1363),
 'getting': np.int64(742),
 'question': np.int64(1630),
 'liao': np.int64(1107),
 'bugis': np.int64(210),
 'frm': np.int64(701),
 'den': np.int64(502),
 'sun': np.int64(1999),
 'cine': np.int64(336),
 'mrt': np.int64(1358),
 'watch': np.int64(2375),
 'yep': np.int64(2482),
 'machan': np.int64(1207),
 'gym': np.int64(853),
 'tomorrow': np.int64(2152),
 'wil': np.int64(2415),
 'goodnight': np.int64(800),
 'as': np.int64(93),
 'rather': np.int64(1650),
 'possible': np.int64(1572),
 'sad': np.int64(1753),
 'er': np.int64(598),
 'sure': np.int64(2010),
 'supposed': np.int64(2009),
 'wot': np.int64(2454),
 'nite': np.int64(1411),
 'hey babe': np.int64(901),
 'somewhere': np.int64(1904),
 'moon': np.int64(1342),
 'light': np.int64(1112),
 'dream': np.int64(548),
 'true': np.int64(2186),
 'light someone': np.int64(1113),
 'amp sweet': np.int64(46),
 'sweet dream': np.int64(2016),
 'amp sweet dream': np.int64(47),
 'job': np.int64(1030),
 'got new': np.int64(807),
 'new job': np.int64(1397),
 'lookin': np.int64(1150),
 'wiv': np.int64(2432),
 'married': np.int64(1232),
 'next': np.int64(1403),
 'sort': np.int64(1913),
 'hp': np.int64(957),
 'next week': np.int64(1404),
 'hp fl': np.int64(958),
 'ill': np.int64(983),
 'good day': np.int64(789),
 'sure get': np.int64(2011),
 'theory': np.int64(2090),
 'argument': np.int64(84),
 'win': np.int64(2417),
 'situation': np.int64(1875),
 'person': np.int64(1504),
 'kick': np.int64(1047),
 'correct': np.int64(431),
 'person dont': np.int64(1505),
 'ur friend': np.int64(2267),
 'outside': np.int64(1481),
 'island': np.int64(1020),
 'towards': np.int64(2173),
 'hard': np.int64(880),
 'rock': np.int64(1738),
 'run': np.int64(1751),
 'leaving': np.int64(1094),
 'house': np.int64(952),
 'tuesday': np.int64(2200),
 'meal': np.int64(1251),
 'mark': np.int64(1230),
 'came': np.int64(272),
 'hostel': np.int64(948),
 'sleep': np.int64(1881),
 'class': np.int64(353),
 'going sleep': np.int64(780),
 'hell': np.int64(895),
 'believe': np.int64(162),
 'forgot': np.int64(671),
 'mr': np.int64(1356),
 'begin': np.int64(160),
 'hate': np.int64(881),
 'didnt': np.int64(506),
 'accept': np.int64(4),
 'even': np.int64(603),
 'single': np.int64(1866),
 'sen': np.int64(1810),
 'kind': np.int64(1049),
 'ready': np.int64(1667),
 'scream': np.int64(1782),
 'get ready': np.int64(735),
 'let': np.int64(1103),
 'missed': np.int64(1303),
 'appreciate': np.int64(76),
 'safe': np.int64(1760),
 'let know': np.int64(1105),
 'great day': np.int64(817),
 'christmas': np.int64(335),
 'midnight': np.int64(1276),
 'working': np.int64(2446),
 'school': np.int64(1780),
 'hungry': np.int64(967),
 'weekend': np.int64(2393),
 'great weekend': np.int64(819),
 'less': np.int64(1101),
 'join': np.int64(1032),
 'bday': np.int64(151),
 'fri': np.int64(693),
 'chikku': np.int64(329),
 'cell': np.int64(311),
 'problem': np.int64(1614),
 'thts': np.int64(2109),
 'nt': np.int64(1430),
 'able': np.int64(1),
 'tea': np.int64(2038),
 'eating': np.int64(569),
 'mom': np.int64(1335),
 'dinner': np.int64(515),
 'vote': np.int64(2346),
 'kallis': np.int64(1040),
 'play': np.int64(1531),
 'first': np.int64(657),
 'two': np.int64(2205),
 'quit': np.int64(1632),
 'till': np.int64(2118),
 'end': np.int64(579),
 'timing': np.int64(2130),
 'paying': np.int64(1495),
 'dad': np.int64(467),
 'pick': np.int64(1515),
 'lar': np.int64(1071),
 'wan': np.int64(2356),
 'stay': np.int64(1951),
 'meh': np.int64(1263),
 'something': np.int64(1902),
 'anymore': np.int64(63),
 'bed': np.int64(156),
 'dun': np.int64(557),
 'already': np.int64(38),
 'start': np.int64(1943),
 'smile': np.int64(1890),
 'trouble': np.int64(2185),
 'rain': np.int64(1641),
 'sum': np.int64(1997),
 'hurt': np.int64(970),
 'smiling': np.int64(1891),
 'long': np.int64(1144),
 'finish': np.int64(655),
 'film': np.int64(646),
 'yet': np.int64(2490),
 'rent': np.int64(1696),
 'past': np.int64(1493),
 'pay': np.int64(1494),
 'charge': np.int64(318),
 'felt': np.int64(640),
 'cost': np.int64(432),
 'however': np.int64(954),
 'askin': np.int64(100),
 'ahead': np.int64(27),
 'neva': np.int64(1394),
 'noe': np.int64(1413),
 'yay': np.int64(2479),
 'party': np.int64(1490),
 'together': np.int64(2149),
 'email': np.int64(576),
 'id': np.int64(976),
 'little': np.int64(1127),
 'track': np.int64(2175),
 'idea': np.int64(977),
 'smoke': np.int64(1892),
 'around': np.int64(86),
 'around lt': np.int64(87),
 'around lt gt': np.int64(88),
 'maybe': np.int64(1250),
 'career': np.int64(291),
 'tel': np.int64(2045),
 'remove': np.int64(1695),
 'glad': np.int64(755),
 'totally': np.int64(2170),
 'shit': np.int64(1842),
 'asleep': np.int64(103),
 'upto': np.int64(2257),
 'hope ok': np.int64(942),
 'car': np.int64(286),
 'key': np.int64(1046),
 'please tell': np.int64(1539),
 'cry': np.int64(454),
 'life': np.int64(1110),
 'die': np.int64(507),
 'keep': np.int64(1044),
 'rose': np.int64(1745),
 'stupid': np.int64(1985),
 'nice day': np.int64(1407),
 'hello': np.int64(897),
 'making': np.int64(1220),
 'cheap': np.int64(324),
 'wine': np.int64(2422),
 'make feel': np.int64(1218),
 'geeee': np.int64(728),
 'loving': np.int64(1178),
 'miss already': np.int64(1299),
 'wait till': np.int64(2351),
 'thk': np.int64(2100),
 'alone': np.int64(37),
 'weight': np.int64(2398),
 'tear': np.int64(2041),
 'fall': np.int64(625),
 'eye': np.int64(621),
 'share': np.int64(1839),
 'come ur': np.int64(391),
 'ur heart': np.int64(2269),
 'nvm': np.int64(1442),
 'surprised': np.int64(2014),
 'went': np.int64(2404),

In [109]:
from sklearn.naive_bayes import MultinomialNB
spmamodel=MultinomialNB().fit(X_train,y_train)

In [110]:
y_pred=spmamodel.predict(X_test)

In [111]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
classification_report(y_test,y_pred)
confusion_m=confusion_matrix(y_test,y_pred)
accuracy=accuracy_score(y_test,y_pred)
print(confusion_m)
print(accuracy)
print(classification_report(y_test,y_pred))

[[132  30]
 [  1 952]]
0.9721973094170404
              precision    recall  f1-score   support

         0.0       0.99      0.81      0.89       162
         1.0       0.97      1.00      0.98       953

    accuracy                           0.97      1115
   macro avg       0.98      0.91      0.94      1115
weighted avg       0.97      0.97      0.97      1115